TAG_BOS = "<START>"
TAG_EOS = "<STOP>"
EMBEDDING_DIM = 5
HIDDEN_DIM = 4
PAD_CHAR = '<CHAR_PAD>'
UNK_WORD = '<UNK>'
PAD_TAG = '<TAG_PAD>'
TAG_SING = 'S'
TAG_BEGIN = 'B'
TAG_MIDDLE = 'M'
TAG_END = 'E'
DATA = './data'
RES = './res'
GOLD = './gold'

